//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquiteturaSample.Site.SvcInstrutor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Instrutor", Namespace="http://schemas.datacontract.org/2004/07/ArquiteturaSample.Entity")]
    [System.SerializableAttribute()]
    public partial class Instrutor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InstrutorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeInstrutorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InstrutorId {
            get {
                return this.InstrutorIdField;
            }
            set {
                if ((this.InstrutorIdField.Equals(value) != true)) {
                    this.InstrutorIdField = value;
                    this.RaisePropertyChanged("InstrutorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeInstrutor {
            get {
                return this.NomeInstrutorField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeInstrutorField, value) != true)) {
                    this.NomeInstrutorField = value;
                    this.RaisePropertyChanged("NomeInstrutor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvcInstrutor.IInstrutor")]
    public interface IInstrutor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstrutor/GetAll", ReplyAction="http://tempuri.org/IInstrutor/GetAllResponse")]
        ArquiteturaSample.Site.SvcInstrutor.Instrutor[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstrutor/GetAll", ReplyAction="http://tempuri.org/IInstrutor/GetAllResponse")]
        System.Threading.Tasks.Task<ArquiteturaSample.Site.SvcInstrutor.Instrutor[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInstrutorChannel : ArquiteturaSample.Site.SvcInstrutor.IInstrutor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InstrutorClient : System.ServiceModel.ClientBase<ArquiteturaSample.Site.SvcInstrutor.IInstrutor>, ArquiteturaSample.Site.SvcInstrutor.IInstrutor {
        
        public InstrutorClient() {
        }
        
        public InstrutorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InstrutorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InstrutorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InstrutorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArquiteturaSample.Site.SvcInstrutor.Instrutor[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ArquiteturaSample.Site.SvcInstrutor.Instrutor[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
